package com.benkih.estore.refund.entity;

import com.benkih.estore.common.entity.BaseEntity;
import com.benkih.estore.common.enums.Currency;
import com.benkih.estore.common.enums.PaymentProvider;
import com.benkih.estore.common.enums.RefundGatewayStatus;
import com.benkih.estore.common.enums.RefundStatus;
import com.benkih.estore.payment.entity.Payment;
import com.benkih.estore.user.entity.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "refunds")
public class Refund extends BaseEntity {

  @Column(nullable = false, unique = true, updatable = false)
  private String slug = UUID.randomUUID().toString();

  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "user_id", nullable = false)
  private User user;

  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "payment_id", nullable = false)
  private Payment payment;

  @Column(nullable = false, precision = 19, scale = 2)
  private BigDecimal amount;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private Currency currency;

  @Enumerated(EnumType.STRING)
  @Column(name = "refund_status", nullable = false)
  private RefundStatus refundStatus = RefundStatus.REQUESTED;

  @Enumerated(EnumType.STRING)
  @Column(name = "gateway_status", nullable = false)
  private RefundGatewayStatus gatewayStatus = RefundGatewayStatus.PENDING;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private PaymentProvider provider;

  /**
   * Refund reference generated by your system.
   */
  @Column(nullable = false, unique = true)
  private String reference;

  /**
   * Refund identifier returned by Paystack/Stripe/etc.
   */
  @Column(unique = true)
  private String gatewayRefundId;

  /**
   * Human-readable reason.
   */
  @Column(length = 1000)
  private String reason;

  /**
   * Raw response from payment gateway.
   */
  @Column(length = 4000)
  private String gatewayResponse;

  /**
   * Failure message if refund fails.
   */
  @Column(length = 1000)
  private String failureReason;

  /**
   * Only needed when refunding to another account.
   * Leave null for normal gateway refunds.
   */
  private String bankCode;
  private String accountNumber;
  private String accountName;

  private LocalDateTime refundedAt;
}