version: "3.9"

services:
  estore:
    build:
      context: .
      dockerfile: Dockerfile

    image: estore:latest
    container_name: estore

    env_file:
      - .env

    ports:
      - "8080:8080"

    restart: unless-stopped