
    create table addresses (
        default_address boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        address_line1 varchar(255) not null,
        address_line2 varchar(255),
        city varchar(255) not null,
        country varchar(255) not null check (country in ('NIGERIA','GHANA','KENYA','SOUTH_AFRICA','UNITED_STATES','UNITED_KINGDOM')),
        created_by varchar(255),
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        phone_number varchar(255) not null,
        postal_code varchar(255),
        slug varchar(255) not null unique,
        state varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table api_logs (
        status_code integer,
        created_at timestamp(6) not null,
        duration_ms bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        trace_id varchar(100),
        user_agent varchar(1000),
        created_by varchar(255),
        endpoint varchar(255) not null,
        exception_message TEXT,
        method varchar(255) not null,
        request_body TEXT,
        request_ip varchar(255),
        response_body TEXT,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        user_email varchar(255),
        user_slug varchar(255),
        primary key (id)
    );

    create table audit_logs (
        created_at timestamp(6) not null,
        entity_id bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        request_ip varchar(45),
        session_id varchar(100),
        trace_id varchar(100),
        user_agent varchar(1000),
        action varchar(255) not null,
        created_by varchar(255),
        entity_slug varchar(255),
        entity_type varchar(255) not null,
        outcome varchar(255),
        slug varchar(255) not null unique,
        status varchar(255) not null,
        updated_by varchar(255),
        user_email varchar(255),
        user_slug varchar(255),
        description oid,
        metadata oid,
        new_value oid,
        old_value oid,
        request oid,
        response oid,
        primary key (id)
    );

    create table cart_items (
        quantity integer not null,
        total_price numeric(38,2),
        unit_price numeric(38,2),
        cart_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint,
        updated_at timestamp(6),
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table carts (
        total_amount numeric(38,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint unique,
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table categories (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(255),
        name varchar(255) not null,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table email_verifications (
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        used_at timestamp(6),
        user_id bigint not null,
        slug varchar(255) not null unique,
        token varchar(255) not null,
        primary key (id)
    );

    create table images (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint,
        updated_at timestamp(6),
        created_by varchar(255),
        download_url varchar(255),
        file_name varchar(255),
        file_path varchar(255) not null,
        file_type varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table order_items (
        price numeric(38,2),
        quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint,
        product_id bigint,
        updated_at timestamp(6),
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table orders (
        discount_amount numeric(18,2) not null,
        shipping_fee numeric(18,2) not null,
        sub_total numeric(18,2) not null,
        tax_amount numeric(18,2) not null,
        total_amount numeric(18,2) not null,
        billing_address_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_date timestamp(6) not null,
        shipping_address_id bigint,
        updated_at timestamp(6),
        user_id bigint not null,
        created_by varchar(255),
        currency varchar(255) not null check (currency in ('NGN','USD','GBP','EUR')),
        notes varchar(255),
        order_number varchar(255) not null unique,
        order_status varchar(255) not null check (order_status in ('PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED')),
        payment_status varchar(255) not null check (payment_status in ('PENDING','PROCESSING','SUCCESS','FAILED','CANCELLED','EXPIRED','UNPAID','PAID','REFUNDED','PARTIALLY_REFUNDED')),
        slug varchar(255) not null unique,
        tracking_number varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table payment_events (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        payment_id bigint not null,
        updated_at timestamp(6),
        created_by varchar(255),
        event_type varchar(255) not null check (event_type in ('INITIALIZED','PENDING','AUTHORIZED','SUCCESS','FAILED','ABANDONED','CANCELLED','REFUNDED','WEBHOOK_RECEIVED','WEBHOOK_VERIFIED')),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        payload TEXT,
        primary key (id)
    );

    create table payments (
        amount numeric(18,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        paid_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint,
        authorization_code varchar(255),
        created_by varchar(255),
        currency varchar(255) not null check (currency in ('NGN','USD','GBP','EUR')),
        failure_reason TEXT,
        gateway_reference TEXT,
        gateway_request TEXT,
        gateway_response TEXT,
        payment_method varchar(255) not null check (payment_method in ('CARD','BANK_TRANSFER','USSD','WALLET','MOBILE_MONEY','CASH_ON_DELIVERY')),
        payment_provider varchar(255) not null check (payment_provider in ('PAYSTACK','FLUTTERWAVE','STRIPE')),
        payment_status varchar(255) not null check (payment_status in ('PENDING','PROCESSING','SUCCESS','FAILED','CANCELLED','EXPIRED','UNPAID','PAID','REFUNDED','PARTIALLY_REFUNDED')),
        reference varchar(255) not null unique,
        slug varchar(255) not null unique,
        transaction_id varchar(255) unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table products (
        inventory integer not null,
        price numeric(38,2),
        category_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        created_by varchar(255),
        description varchar(255),
        name varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table refresh_tokens (
        expired boolean not null,
        revoked boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        ip_address varchar(45),
        device varchar(100),
        token varchar(500) not null unique,
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table reviews (
        rating integer not null,
        verified_purchase boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6),
        user_id bigint not null,
        comment varchar(1000),
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id),
        constraint uk_review_user_product unique (user_id, product_id)
    );

    create table roles (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(255),
        name varchar(255) not null unique,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table users (
        email_verified boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        phone_number varchar(20),
        created_by varchar(255),
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255) not null,
        slug varchar(255) not null unique,
        status varchar(255) not null check (status in ('ACTIVE','INACTIVE','SUSPENDED','BLOCKED','PENDING_VERIFICATION')),
        updated_by varchar(255),
        primary key (id)
    );

    alter table if exists addresses 
       add constraint FK1fa36y2oqhao3wgg2rw1pi459 
       foreign key (user_id) 
       references users;

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FK1re40cjegsfvw58xrkdp6bac6 
       foreign key (product_id) 
       references products;

    alter table if exists carts 
       add constraint FKb5o626f86h46m4s7ms6ginnop 
       foreign key (user_id) 
       references users;

    alter table if exists email_verifications 
       add constraint FKou1xuy3rdeao75p2x1v4v3xs 
       foreign key (user_id) 
       references users;

    alter table if exists images 
       add constraint FKghwsjbjo7mg3iufxruvq6iu3q 
       foreign key (product_id) 
       references products;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FK66jolu65brloux12yi37qy3ky 
       foreign key (billing_address_id) 
       references addresses;

    alter table if exists orders 
       add constraint FKmk6q95x8ffidq82wlqjaq7sqc 
       foreign key (shipping_address_id) 
       references addresses;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists payment_events 
       add constraint FKe86hr8sww5wcn9aiilg8ykchi 
       foreign key (payment_id) 
       references payments;

    alter table if exists payments 
       add constraint FK81gagumt0r8y3rmudcgpbk42l 
       foreign key (order_id) 
       references orders;

    alter table if exists payments 
       add constraint FKj94hgy9v5fw1munb90tar2eje 
       foreign key (user_id) 
       references users;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    alter table if exists reviews 
       add constraint FKpl51cejpw4gy5swfar8br9ngi 
       foreign key (product_id) 
       references products;

    alter table if exists reviews 
       add constraint FKcgy7qjc1r99dp117y9en6lxye 
       foreign key (user_id) 
       references users;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
