spring.application.name=e-store

# Database Configuration - Using Environment Variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
auth.token.jwtSecret=${JWT_SECRET}
auth.token.expirationInMils=${JWT_EXPIRATION}

# Upload Directory
app.upload.dir=${UPLOAD_DIR}

# Server Configuration
server.port=${SERVER_PORT}
api.prefix=${API_PREFIX}

# Spring Configuration
spring.flyway.enabled=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Logging
logging.level.org.flywaydb=${FLYWAY_LOG_LEVEL}
logging.level.org.springframework.boot.autoconfigure.flyway=${FLYWAY_LOG_LEVEL}


## create||update||validate: production||create-drop || none
## application-dev.properties
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#logging.level.com.benkih.estore=DEBUG

# application-prod.properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
# WARN, DEBUG, INFO
logging.level.com.benkih.estore=DEBUG

#Mails
app.email.provider=mailtrap

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

paystack.base-url=${PAYSTACK_BASE_URL}
paystack.secret-key=${PAYSTACK_SECRET_KEY}


# The below properties are used to run [./mvnw clean install], with this set
# to none [spring.jpa.hibernate.ddl-auto=none] to create the V1__initial_schema.sql file which
# generates the first migration file, I also made sure all the seeder files are commented out.
# Then after that, I commented the below properties and enabled this [spring.flyway.enabled=true]
# and this set to validate [spring.jpa.hibernate.ddl-auto=validate] then I ran this [./mvnw spring-boot:run]
# to start which allows flyway to create the tables and not hibernate. After the tables has been created,
# now I could uncomment the seeder file and ran the app [./mvnw spring-boot:run] once again

#spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/db/migration/V1__initial_schema.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
#spring.flyway.enabled=false





#spring.flyway.enabled=true
# Flyway debugging
#logging.level.org.flywaydb=DEBUG
#logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

#spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE