spring.application.name=e-store

server.port=8070

spring.datasource.url=jdbc:postgresql://localhost:5432/estore_database
spring.datasource.username=postgres
spring.datasource.password=testing123

## create||update||validate: production||create-drop || none
spring.jpa.hibernate.ddl-auto=validate

# The below properties are used to run [./mvnw clean install], with this set
# to none [spring.jpa.hibernate.ddl-auto=none] to create the V1__initial_schema.sql file which
# generates the first migration file, I also made sure all the seeder files are commented out.
# Then after that, I commented the below properties and enabled this [spring.flyway.enabled=true]
# and this set to validate [spring.jpa.hibernate.ddl-auto=validate] then I ran this [./mvnw spring-boot:run]
# to start which allows flyway to create the tables and not hibernate. After the tables has been created,
# not I could uncomment the seeder file and ran the app [./mvnw spring-boot:run] once again

#spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/db/migration/V1__initial_schema.sql
#spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
#spring.flyway.enabled=false

spring.flyway.enabled=true
# Flyway debugging
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

spring.jpa.open-in-view=false
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#app.upload.dir=uploads/images
app.upload.dir=/Users/macbook/Downloads/e-store/uploads/images

auth.token.expirationInMils=3600000
auth.token.jwtSecret=Dx8sK9fQ3wE5rT7yU9iL0oP2aM4nB6cV8xZ1bC3dE5fG7hJ9kL1mN2oP3qR4sT6uV8wX0yZ2

api.prefix=/api/v1

