

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.jakarta.persistence.schema-generation.database.action=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/main/resources/database/migration/V1__initial_schema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
