
    create table addresses (
        default_address boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null,
        address_line1 varchar(255) not null,
        address_line2 varchar(255),
        city varchar(255) not null,
        country varchar(255) not null check (country in ('NIGERIA','GHANA','KENYA','SOUTH_AFRICA','UNITED_STATES','UNITED_KINGDOM')),
        created_by varchar(255),
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        phone_number varchar(255) not null,
        postal_code varchar(255),
        slug varchar(255) not null unique,
        state varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table allocations (
        currency varchar(3) not null check (currency in ('NGN','USD','GBP','EUR')),
        discount_amount numeric(18,2) not null,
        gross_amount numeric(18,2) not null,
        net_amount numeric(18,2) not null,
        payment_fee numeric(18,2) not null,
        platform_fee numeric(18,2) not null,
        refund_amount numeric(18,2) not null,
        shipping_amount numeric(18,2) not null,
        tax_amount numeric(18,2) not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_item_id bigint not null,
        payment_id bigint not null,
        updated_at timestamp(6),
        slug varchar(255) not null unique,
        status varchar(255) not null check (status in ('PENDING','AVAILABLE','SETTLED','PAID','REFUNDED','PARTIALLY_REFUNDED','CANCELLED')),
        primary key (id)
    );

    create table api_logs (
        status_code integer,
        created_at timestamp(6) not null,
        duration_ms bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        trace_id varchar(100),
        user_agent varchar(1000),
        created_by varchar(255),
        endpoint varchar(255) not null,
        exception_message TEXT,
        method varchar(255) not null,
        request_body TEXT,
        request_ip varchar(255),
        response_body TEXT,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        user_email varchar(255),
        user_slug varchar(255),
        primary key (id)
    );

    create table attribute_values (
        active boolean not null,
        display_order integer not null,
        attribute_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        display_name varchar(100),
        value varchar(100) not null,
        slug varchar(255) not null unique,
        primary key (id),
        constraint uk_attribute_value unique (attribute_id, value)
    );

    create table audit_logs (
        created_at timestamp(6) not null,
        entity_id bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        request_ip varchar(45),
        session_id varchar(100),
        trace_id varchar(100),
        user_agent varchar(1000),
        action varchar(255) not null,
        created_by varchar(255),
        entity_slug varchar(255),
        entity_type varchar(255) not null,
        outcome varchar(255),
        slug varchar(255) not null unique,
        status varchar(255) not null,
        updated_by varchar(255),
        user_email varchar(255),
        user_slug varchar(255),
        description oid,
        metadata oid,
        new_value oid,
        old_value oid,
        request oid,
        response oid,
        primary key (id)
    );

    create table bank_accounts (
        default_account boolean not null,
        verified boolean not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        account_name varchar(255) not null,
        account_number varchar(255) not null,
        bank_code varchar(255) not null,
        bank_name varchar(255) not null,
        slug varchar(255) not null unique,
        primary key (id)
    );

    create table business_addresses (
        active boolean not null,
        default_address boolean not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        type varchar(30) not null check (type in ('REGISTERED','BILLING','FULFILLMENT','WAREHOUSE','RETURN')),
        address_line1 varchar(255) not null,
        address_line2 varchar(255),
        address_name varchar(255) not null,
        city varchar(255) not null,
        country varchar(255) not null check (country in ('NIGERIA','GHANA','KENYA','SOUTH_AFRICA','UNITED_STATES','UNITED_KINGDOM')),
        created_by varchar(255),
        phone_number varchar(255) not null,
        postal_code varchar(255),
        slug varchar(255) not null unique,
        state varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table business_member_departments (
        business_member_id bigint not null,
        department_id bigint not null,
        primary key (business_member_id, department_id)
    );

    create table business_member_roles (
        business_member_id bigint not null,
        role_id bigint not null,
        primary key (business_member_id, role_id)
    );

    create table business_members (
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint not null unique,
        slug varchar(255) not null unique,
        status varchar(255) not null check (status in ('ACTIVE','INVITED','SUSPENDED','REMOVED')),
        primary key (id)
    );

    create table business_settings (
        invoice_enabled boolean not null,
        business_id bigint not null unique,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        currency varchar(255) not null check (currency in ('NGN','USD','GBP','EUR')),
        invoice_prefix varchar(255),
        order_prefix varchar(255),
        slug varchar(255) not null unique,
        timezone varchar(255),
        primary key (id)
    );

    create table businesses (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255) not null,
        legal_name varchar(255),
        logo_url varchar(255),
        name varchar(255) not null,
        phone varchar(255),
        slug varchar(255) not null unique,
        status varchar(255) not null check (status in ('PENDING','ACTIVE','SUSPENDED','DEACTIVATED')),
        type varchar(255) not null check (type in ('INDIVIDUAL','COMPANY')),
        website varchar(255),
        primary key (id)
    );

    create table cart_items (
        quantity integer not null check (quantity>=1),
        total_price numeric(19,2) not null,
        unit_price numeric(19,2) not null,
        cart_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        variant_id bigint not null,
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id),
        constraint uk_cart_variant unique (cart_id, variant_id)
    );

    create table carts (
        total_amount numeric(38,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint unique,
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table categories (
        active boolean not null,
        display_order integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        parent_id bigint,
        updated_at timestamp(6),
        name varchar(150) not null,
        created_by varchar(255),
        description TEXT,
        image_url varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id),
        constraint uk_category_parent_name unique (parent_id, name)
    );

    create table category_attributes (
        active boolean not null,
        display_order integer not null,
        required boolean not null,
        variant_attribute boolean not null,
        category_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        type varchar(30) not null check (type in ('TEXT','NUMBER','BOOLEAN','SELECT','MULTI_SELECT','COLOR','SIZE')),
        name varchar(100) not null,
        slug varchar(255) not null unique,
        primary key (id),
        constraint uk_category_attribute unique (category_id, name)
    );

    create table customer_addresses (
        default_address boolean not null,
        created_at timestamp(6) not null,
        customer_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        address_line1 varchar(255) not null,
        address_line2 varchar(255),
        city varchar(255) not null,
        country varchar(255) not null check (country in ('NIGERIA','GHANA','KENYA','SOUTH_AFRICA','UNITED_STATES','UNITED_KINGDOM')),
        created_by varchar(255),
        phone_number varchar(255),
        postal_code varchar(255),
        slug varchar(255) not null unique,
        state varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table customers (
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint,
        email varchar(255),
        name varchar(255) not null,
        phone varchar(255),
        slug varchar(255) not null unique,
        primary key (id)
    );

    create table departments (
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(255),
        description varchar(255),
        name varchar(255) not null,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id),
        constraint uk_department_business_name unique (business_id, name)
    );

    create table email_verifications (
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        used_at timestamp(6),
        user_id bigint not null,
        slug varchar(255) not null unique,
        token varchar(255) not null,
        primary key (id)
    );

    create table images (
        display_order integer not null,
        primary_image boolean not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6),
        alt_text varchar(255),
        created_by varchar(255),
        download_url varchar(255),
        file_name varchar(255),
        file_path varchar(255) not null,
        file_type varchar(255),
        slug varchar(255) not null unique,
        storage_key varchar(255) not null,
        updated_by varchar(255),
        primary key (id)
    );

    create table inventories (
        damaged_stock integer not null,
        reorder_level integer not null,
        reorder_quantity integer not null,
        reserved_stock integer not null,
        total_stock integer not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        variant_id bigint not null unique,
        version bigint,
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table inventory_movements (
        quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        inventory_id bigint not null,
        updated_at timestamp(6),
        type varchar(30) not null check (type in ('STOCK_IN','RESERVE','RELEASE','FULFILL','DAMAGE','RETURN','ADJUSTMENT')),
        reference_type varchar(50),
        reference_id varchar(100),
        reason varchar(500),
        slug varchar(255) not null unique,
        primary key (id)
    );

    create table inventory_reservations (
        quantity integer not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        inventory_id bigint not null,
        updated_at timestamp(6),
        status varchar(20) not null check (status in ('ACTIVE','RELEASED','FULFILLED','EXPIRED')),
        checkout_reference varchar(100) not null,
        slug varchar(255) not null unique,
        primary key (id)
    );

    create table order_idempotency (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint not null unique,
        updated_at timestamp(6),
        user_id bigint not null,
        idempotency_key varchar(100) not null,
        slug varchar(255) not null unique,
        primary key (id),
        constraint uk_order_idempotency_user_key unique (user_id, idempotency_key)
    );

    create table order_items (
        currency varchar(3) not null check (currency in ('NGN','USD','GBP','EUR')),
        discount_amount numeric(19,2) not null,
        price numeric(18,2) not null,
        quantity integer not null,
        subtotal numeric(19,2) not null,
        tax_amount numeric(19,2) not null,
        tax_rate numeric(8,5) not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint,
        product_id bigint,
        updated_at timestamp(6),
        variant_id bigint,
        brand varchar(255),
        created_by varchar(255),
        name varchar(255) not null,
        sku varchar(255) not null,
        slug varchar(255) not null unique,
        tax_category varchar(255) not null check (tax_category in ('STANDARD','ZERO_RATED','EXEMPT')),
        updated_by varchar(255),
        primary key (id)
    );

    create table orders (
        discount_amount numeric(18,2) not null,
        shipping_fee numeric(18,2) not null,
        sub_total numeric(18,2) not null,
        tax_amount numeric(18,2) not null,
        total_amount numeric(18,2) not null,
        billing_address_id bigint,
        cancelled_at timestamp(6),
        completed_at timestamp(6),
        created_at timestamp(6) not null,
        delivered_at timestamp(6),
        id bigint generated by default as identity,
        order_date timestamp(6) not null,
        paid_at timestamp(6),
        shipped_at timestamp(6),
        shipping_address_id bigint,
        updated_at timestamp(6),
        user_id bigint not null,
        created_by varchar(255),
        currency varchar(255) not null check (currency in ('NGN','USD','GBP','EUR')),
        notes varchar(255),
        order_number varchar(255) not null unique,
        order_status varchar(255) not null check (order_status in ('EXPIRED','PENDING','CONFIRMED','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURN_REQUESTED','RETURNED')),
        payment_status varchar(255) not null check (payment_status in ('PENDING','PAID','PROCESSING','SUCCESS','FAILED','CANCELLED','EXPIRED','REFUNDED','PARTIALLY_REFUNDED')),
        slug varchar(255) not null unique,
        tracking_number varchar(255),
        updated_by varchar(255),
        primary key (id)
    );

    create table password_reset_tokens (
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        used_at timestamp(6),
        user_id bigint not null,
        slug varchar(255) not null unique,
        token_hash varchar(255) not null,
        primary key (id)
    );

    create table payment_events (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        payment_id bigint not null,
        updated_at timestamp(6),
        created_by varchar(255),
        event_type varchar(255) not null check (event_type in ('INITIALIZED','PENDING','AUTHORIZED','SUCCESS','FAILED','ABANDONED','CANCELLED','REFUNDED','WEBHOOK_RECEIVED','WEBHOOK_VERIFIED')),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        payload TEXT,
        primary key (id)
    );

    create table payments (
        amount numeric(18,2) not null,
        processor_fee numeric(18,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        paid_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint,
        authorization_url varchar(500),
        access_code varchar(255),
        authorization_code varchar(255),
        created_by varchar(255),
        currency varchar(255) not null check (currency in ('NGN','USD','GBP','EUR')),
        failure_reason TEXT,
        gateway_reference TEXT,
        gateway_request TEXT,
        gateway_response TEXT,
        payment_method varchar(255) not null check (payment_method in ('CARD','BANK_TRANSFER','USSD','WALLET','MOBILE_MONEY','CASH_ON_DELIVERY')),
        payment_provider varchar(255) not null check (payment_provider in ('PAYSTACK','FLUTTERWAVE','STRIPE')),
        payment_status varchar(255) not null check (payment_status in ('PENDING','PAID','PROCESSING','SUCCESS','FAILED','CANCELLED','EXPIRED','REFUNDED','PARTIALLY_REFUNDED')),
        reference varchar(255) not null unique,
        slug varchar(255) not null unique,
        transaction_id varchar(255) unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table permissions (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        action varchar(255) not null,
        created_by varchar(255),
        description varchar(255),
        name varchar(255) not null unique,
        resource varchar(255) not null,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id),
        constraint uk_permission_resource_action unique (resource, action)
    );

    create table product_attributes (
        attribute_id bigint not null,
        attribute_value_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6),
        custom_value varchar(255),
        slug varchar(255) not null unique,
        primary key (id),
        constraint uk_product_attribute unique (product_id, attribute_id)
    );

    create table product_variant_attributes (
        attribute_id bigint not null,
        attribute_value_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        variant_id bigint not null,
        custom_value varchar(255),
        slug varchar(255) not null unique,
        primary key (id),
        constraint uk_variant_attribute unique (variant_id, attribute_id)
    );

    create table product_variants (
        active boolean not null,
        currency varchar(3) not null check (currency in ('NGN','USD','GBP','EUR')),
        price numeric(19,2) not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6),
        sku varchar(100) not null,
        combination_key varchar(500) not null,
        slug varchar(255) not null unique,
        primary key (id),
        constraint uk_variant_business_sku unique (business_id, sku),
        constraint uk_variant_product_combination unique (product_id, combination_key)
    );

    create table products (
        height_cm numeric(10,2),
        length_cm numeric(10,2),
        return_window_days integer not null,
        returnable boolean not null,
        shippable boolean not null,
        warranty_months integer not null,
        weight_kg numeric(10,3) not null,
        width_cm numeric(10,2),
        archived_at timestamp(6) with time zone,
        business_id bigint not null,
        category_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        gtin varchar(14),
        condition varchar(20) not null check (condition in ('NEW','USED','REFURBISHED')),
        status varchar(30) not null check (status in ('DRAFT','ACTIVE','ARCHIVED','READY_FOR_REVIEW','APPROVED')),
        tax_category varchar(30) not null check (tax_category in ('STANDARD','ZERO_RATED','EXEMPT')),
        barcode varchar(50),
        brand varchar(100),
        manufacturer varchar(100),
        model varchar(100),
        created_by varchar(255),
        description TEXT,
        name varchar(255) not null,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table promotion_redemptions (
        discount_amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        promotion_id bigint not null,
        redeemed_at timestamp(6) with time zone not null,
        updated_at timestamp(6),
        user_id bigint,
        slug varchar(255) not null unique,
        primary key (id),
        constraint uk_promotion_order unique (promotion_id, order_id)
    );

    create table promotions (
        active boolean not null,
        amount numeric(18,2),
        maximum_discount numeric(18,2),
        minimum_order_amount numeric(18,2),
        percentage numeric(5,2),
        usage_count integer not null,
        usage_limit integer,
        created_at timestamp(6) not null,
        expires_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        starts_at timestamp(6) with time zone,
        updated_at timestamp(6),
        code varchar(255) not null unique,
        name varchar(255) not null,
        slug varchar(255) not null unique,
        type varchar(255) not null check (type in ('PERCENTAGE','FIXED_AMOUNT')),
        primary key (id)
    );

    create table refresh_tokens (
        revoked boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        last_used_at timestamp(6),
        revoked_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        device varchar(255),
        ip_address varchar(255),
        revoked_reason varchar(255) check (revoked_reason in ('LOGOUT','ROTATED','PASSWORD_CHANGED','ADMIN_REVOKED','SECURITY_EVENT','LOGOUT_ALL_DEVICES')),
        slug varchar(255) not null unique,
        token_hash varchar(255) not null,
        primary key (id)
    );

    create table refund_items (
        amount numeric(19,2) not null,
        quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_item_id bigint not null,
        refund_id bigint not null,
        updated_at timestamp(6),
        slug varchar(255) not null unique,
        primary key (id),
        constraint uq_refund_item unique (refund_id, order_item_id)
    );

    create table refunds (
        amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        payment_id bigint not null,
        refunded_at timestamp(6),
        updated_at timestamp(6),
        user_id bigint not null,
        failure_reason varchar(1000),
        reason varchar(1000),
        gateway_response varchar(4000),
        account_name varchar(255),
        account_number varchar(255),
        bank_code varchar(255),
        currency varchar(255) not null check (currency in ('NGN','USD','GBP','EUR')),
        gateway_refund_id varchar(255) unique,
        gateway_status varchar(255) not null check (gateway_status in ('PENDING','PROCESSING','NEEDS_ATTENTION','FAILED','PROCESSED','SUCCESS','UNKNOWN')),
        provider varchar(255) not null check (provider in ('PAYSTACK','FLUTTERWAVE','STRIPE')),
        reference varchar(255) not null unique,
        refund_status varchar(255) not null check (refund_status in ('REQUESTED','APPROVED','REJECTED')),
        slug varchar(255) not null unique,
        primary key (id)
    );

    create table reviews (
        rating integer not null,
        verified_purchase boolean not null,
        business_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        updated_at timestamp(6),
        user_id bigint not null,
        comment varchar(1000),
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id),
        constraint uk_review_user_product unique (user_id, product_id)
    );

    create table role_permissions (
        permission_id bigint not null,
        role_id bigint not null,
        primary key (permission_id, role_id)
    );

    create table roles (
        active boolean not null,
        system_role boolean not null,
        business_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        description varchar(500),
        created_by varchar(255),
        name varchar(255) not null,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id),
        constraint uk_role_business_name unique (business_id, name)
    );

    create table shipping_rates (
        active boolean not null,
        currency varchar(3) not null check (currency in ('NGN','USD','GBP','EUR')),
        fee numeric(18,2) not null,
        free_shipping_threshold numeric(18,2),
        max_weight_kg numeric(10,2),
        min_weight_kg numeric(10,2) not null,
        created_at timestamp(6) not null,
        effective_from timestamp(6) with time zone not null,
        effective_to timestamp(6) with time zone,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        delivery_method varchar(50) not null,
        zone varchar(50) not null,
        code varchar(255) not null unique,
        slug varchar(255) not null unique,
        primary key (id)
    );

    create table tax_rules (
        active boolean not null,
        rate numeric(8,5) not null,
        created_at timestamp(6) not null,
        effective_from timestamp(6) not null,
        effective_to timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        tax_category varchar(30) not null check (tax_category in ('STANDARD','ZERO_RATED','EXEMPT')),
        tax_type varchar(30) not null,
        country varchar(50) not null check (country in ('NIGERIA','GHANA','KENYA','SOUTH_AFRICA','UNITED_STATES','UNITED_KINGDOM')),
        jurisdiction varchar(50) not null,
        code varchar(255) not null unique,
        slug varchar(255) not null unique,
        primary key (id)
    );

    create table user_departments (
        department_id bigint not null,
        user_id bigint not null,
        primary key (department_id, user_id)
    );

    create table user_invitation_departments (
        department_id bigint not null,
        invitation_id bigint not null,
        primary key (department_id, invitation_id)
    );

    create table user_invitation_roles (
        invitation_id bigint not null,
        role_id bigint not null,
        primary key (invitation_id, role_id)
    );

    create table user_invitations (
        accepted_at timestamp(6),
        business_id bigint not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        invited_by bigint,
        updated_at timestamp(6),
        created_by varchar(255),
        email varchar(255) not null,
        first_name varchar(255),
        last_name varchar(255),
        phone_number varchar(255),
        slug varchar(255) not null unique,
        status varchar(255) not null check (status in ('PENDING','ACCEPTED','EXPIRED','CANCELLED')),
        token_hash varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table users (
        email_verified boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        phone_number varchar(20),
        account_type varchar(255) not null check (account_type in ('PERSONAL','BUSINESS')),
        created_by varchar(255),
        email varchar(255) not null unique,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        password varchar(255),
        slug varchar(255) not null unique,
        status varchar(255) not null check (status in ('ACTIVE','INACTIVE','SUSPENDED','BLOCKED','PENDING_VERIFICATION')),
        updated_by varchar(255),
        primary key (id)
    );

    create index idx_departments_business_id 
       on departments (business_id);

    create index idx_departments_business_name 
       on departments (business_id, name);

    create index idx_inventory_movements_inventory 
       on inventory_movements (inventory_id, created_at);

    create index idx_inventory_movements_reference 
       on inventory_movements (reference_type, reference_id);

    create index idx_inventory_reservation_checkout 
       on inventory_reservations (checkout_reference);

    create index idx_inventory_reservation_expiry 
       on inventory_reservations (status, expires_at);

    create index idx_password_reset_user 
       on password_reset_tokens (user_id);

    create index idx_password_reset_slug 
       on password_reset_tokens (slug);

    create index idx_permissions_name 
       on permissions (name);

    create index idx_permissions_resource_action 
       on permissions (resource, action);

    create index idx_promotions_code 
       on promotions (code);

    create index idx_promotions_active_dates 
       on promotions (active, starts_at, expires_at);

    create index idx_refresh_user 
       on refresh_tokens (user_id);

    create index idx_refresh_expires 
       on refresh_tokens (expires_at);

    create index idx_reviews_business_id 
       on reviews (business_id);

    create index idx_reviews_business_product 
       on reviews (business_id, product_id);

    create index idx_roles_slug 
       on roles (slug);

    create index idx_roles_name 
       on roles (name);

    create index idx_roles_business_id 
       on roles (business_id);

    create index idx_shipping_rates_lookup 
       on shipping_rates (zone, delivery_method, min_weight_kg, max_weight_kg);

    create index idx_tax_rules_lookup 
       on tax_rules (jurisdiction, tax_category, effective_from, effective_to);

    create index idx_invitation_email 
       on user_invitations (email);

    create index idx_invitation_token 
       on user_invitations (token_hash);

    create index idx_invitation_status 
       on user_invitations (status);

    create index idx_invitation_expiry 
       on user_invitations (expires_at);

    create index idx_invitation_business_id 
       on user_invitations (business_id);

    alter table if exists addresses 
       add constraint FK1fa36y2oqhao3wgg2rw1pi459 
       foreign key (user_id) 
       references users;

    alter table if exists allocations 
       add constraint FKrq1vhgh34to3xt6ylx0kvnbbp 
       foreign key (business_id) 
       references businesses;

    alter table if exists allocations 
       add constraint FKejwbatnj62uglomxcc5cphv3c 
       foreign key (order_item_id) 
       references order_items;

    alter table if exists allocations 
       add constraint FKhq06uos48sj7cwrhjmdtw2dq8 
       foreign key (payment_id) 
       references payments;

    alter table if exists attribute_values 
       add constraint FKmlf3070qt2fh704ekpcd8qfmb 
       foreign key (attribute_id) 
       references category_attributes;

    alter table if exists bank_accounts 
       add constraint FKorn8djkexni8i7piw4tj52avb 
       foreign key (business_id) 
       references businesses;

    alter table if exists business_addresses 
       add constraint FK229ht2n6vwmx6hilmde9whrxa 
       foreign key (business_id) 
       references businesses;

    alter table if exists business_member_departments 
       add constraint FK4qrotnbo04xv43wc6h99yedsa 
       foreign key (department_id) 
       references departments;

    alter table if exists business_member_departments 
       add constraint FKlsmrwx8dhk6vnkyri0bqng999 
       foreign key (business_member_id) 
       references business_members;

    alter table if exists business_member_roles 
       add constraint FK6phto8vssjkyqxklcstutjdq3 
       foreign key (role_id) 
       references roles;

    alter table if exists business_member_roles 
       add constraint FKago1sgx5fb0jsvpnv2c2s4tta 
       foreign key (business_member_id) 
       references business_members;

    alter table if exists business_members 
       add constraint FKo01cepu6mek8gfi8k0sr9epxg 
       foreign key (business_id) 
       references businesses;

    alter table if exists business_members 
       add constraint FKl3se6j2mob8wdx6tjckpx0qjt 
       foreign key (user_id) 
       references users;

    alter table if exists business_settings 
       add constraint FKihgi2bjtgvfl1wj8s9354849j 
       foreign key (business_id) 
       references businesses;

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FK5yyw1o0dor9gmxfra1dqvn4qa 
       foreign key (variant_id) 
       references product_variants;

    alter table if exists carts 
       add constraint FKb5o626f86h46m4s7ms6ginnop 
       foreign key (user_id) 
       references users;

    alter table if exists categories 
       add constraint FKsaok720gsu4u2wrgbk10b5n8d 
       foreign key (parent_id) 
       references categories;

    alter table if exists category_attributes 
       add constraint FKs8x8saggy3b3wx581pn813por 
       foreign key (category_id) 
       references categories;

    alter table if exists customer_addresses 
       add constraint FKrvr6wl9gll7u98cda18smugp4 
       foreign key (customer_id) 
       references customers;

    alter table if exists customers 
       add constraint FKjjod36f7buv2adeptxcfec8jm 
       foreign key (business_id) 
       references businesses;

    alter table if exists customers 
       add constraint FKrh1g1a20omjmn6kurd35o3eit 
       foreign key (user_id) 
       references users;

    alter table if exists departments 
       add constraint FKc6b7ln09ux6j91xquint6m6xm 
       foreign key (business_id) 
       references businesses;

    alter table if exists email_verifications 
       add constraint FKou1xuy3rdeao75p2x1v4v3xs 
       foreign key (user_id) 
       references users;

    alter table if exists images 
       add constraint FKqyfra8q8fgaw30q8pwwtr9efa 
       foreign key (business_id) 
       references businesses;

    alter table if exists images 
       add constraint FKghwsjbjo7mg3iufxruvq6iu3q 
       foreign key (product_id) 
       references products;

    alter table if exists inventories 
       add constraint FK7vt5ueo57co869193okf7ns02 
       foreign key (business_id) 
       references businesses;

    alter table if exists inventories 
       add constraint FK1hwr2nkixleellrw6uthechom 
       foreign key (variant_id) 
       references product_variants;

    alter table if exists inventory_movements 
       add constraint FKoxyuibrvriwucfhbhi5qc25l9 
       foreign key (inventory_id) 
       references inventories;

    alter table if exists inventory_reservations 
       add constraint FK6m92xy8d8eeryn175y0ou1wrk 
       foreign key (inventory_id) 
       references inventories;

    alter table if exists order_idempotency 
       add constraint FKfvlkp2fl13vx8cxyx66rm8dhs 
       foreign key (order_id) 
       references orders;

    alter table if exists order_idempotency 
       add constraint FKrutuid8r355fh7r3cgsnam9t6 
       foreign key (user_id) 
       references users;

    alter table if exists order_items 
       add constraint FKcn38le6ny06tr9pcm1l9y6fgf 
       foreign key (business_id) 
       references businesses;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists order_items 
       add constraint FKemq71edpbn9wsxnxncfn1algp 
       foreign key (variant_id) 
       references product_variants;

    alter table if exists orders 
       add constraint FK66jolu65brloux12yi37qy3ky 
       foreign key (billing_address_id) 
       references addresses;

    alter table if exists orders 
       add constraint FKmk6q95x8ffidq82wlqjaq7sqc 
       foreign key (shipping_address_id) 
       references addresses;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists password_reset_tokens 
       add constraint FKk3ndxg5xp6v7wd4gjyusp15gq 
       foreign key (user_id) 
       references users;

    alter table if exists payment_events 
       add constraint FKe86hr8sww5wcn9aiilg8ykchi 
       foreign key (payment_id) 
       references payments;

    alter table if exists payments 
       add constraint FK81gagumt0r8y3rmudcgpbk42l 
       foreign key (order_id) 
       references orders;

    alter table if exists payments 
       add constraint FKj94hgy9v5fw1munb90tar2eje 
       foreign key (user_id) 
       references users;

    alter table if exists product_attributes 
       add constraint FKp4wqnxdw5e8qtx1neohjaelh8 
       foreign key (attribute_id) 
       references category_attributes;

    alter table if exists product_attributes 
       add constraint FKjdu92f42xssexo648j43anl0 
       foreign key (attribute_value_id) 
       references attribute_values;

    alter table if exists product_attributes 
       add constraint FKcex46yvx4g18b2pn09p79h1mc 
       foreign key (product_id) 
       references products;

    alter table if exists product_variant_attributes 
       add constraint FK9iav42m83yknpbij3vo718c6g 
       foreign key (attribute_id) 
       references category_attributes;

    alter table if exists product_variant_attributes 
       add constraint FKls307hv852202qflf6njny691 
       foreign key (attribute_value_id) 
       references attribute_values;

    alter table if exists product_variant_attributes 
       add constraint FKjcp7i8t08la8masfe513eisnv 
       foreign key (variant_id) 
       references product_variants;

    alter table if exists product_variants 
       add constraint FKnaddjmvjemof291xohnxtooqn 
       foreign key (business_id) 
       references businesses;

    alter table if exists product_variants 
       add constraint FKosqitn4s405cynmhb87lkvuau 
       foreign key (product_id) 
       references products;

    alter table if exists products 
       add constraint FKi65q12p725kxcn1jcosg2x9y4 
       foreign key (business_id) 
       references businesses;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;

    alter table if exists promotion_redemptions 
       add constraint FKcudyexc9rwj3tqpmi2hf6axt3 
       foreign key (order_id) 
       references orders;

    alter table if exists promotion_redemptions 
       add constraint FK532mn698okly0glbnl33tloi5 
       foreign key (promotion_id) 
       references promotions;

    alter table if exists promotion_redemptions 
       add constraint FKe2f1srjlqws7cdjpy7b9cahry 
       foreign key (user_id) 
       references users;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    alter table if exists refund_items 
       add constraint FKt30eqahpu8nehh4y98ik6c4i2 
       foreign key (order_item_id) 
       references order_items;

    alter table if exists refund_items 
       add constraint FKrmpg1ehoqwl6q0aql0679jpnd 
       foreign key (refund_id) 
       references refunds;

    alter table if exists refunds 
       add constraint FKpt9ic0j1y6xwlej99wnynvnpy 
       foreign key (payment_id) 
       references payments;

    alter table if exists refunds 
       add constraint FKrtxief4co3k1lfklj7n05m8mo 
       foreign key (user_id) 
       references users;

    alter table if exists reviews 
       add constraint FK459hpq39fs05s70les78oa7qk 
       foreign key (business_id) 
       references businesses;

    alter table if exists reviews 
       add constraint FKpl51cejpw4gy5swfar8br9ngi 
       foreign key (product_id) 
       references products;

    alter table if exists reviews 
       add constraint FKcgy7qjc1r99dp117y9en6lxye 
       foreign key (user_id) 
       references users;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists roles 
       add constraint FKfrkn4puuuw970vw5c2rsdn0le 
       foreign key (business_id) 
       references businesses;

    alter table if exists user_departments 
       add constraint FKe1yilu7bslmau7ojj0n2pu812 
       foreign key (department_id) 
       references departments;

    alter table if exists user_departments 
       add constraint FKeklynfw1mm4x2289n61pj0ojn 
       foreign key (user_id) 
       references users;

    alter table if exists user_invitation_departments 
       add constraint FKbt5ggs3dgg0ncms43ow1w54aj 
       foreign key (department_id) 
       references departments;

    alter table if exists user_invitation_departments 
       add constraint FKq4r1vf27jh8137f2xfyw9ba0n 
       foreign key (invitation_id) 
       references user_invitations;

    alter table if exists user_invitation_roles 
       add constraint FKc9c39yu29fy9022q1vu992ael 
       foreign key (role_id) 
       references roles;

    alter table if exists user_invitation_roles 
       add constraint FKcktv262s50sle5pxgac0p3wrp 
       foreign key (invitation_id) 
       references user_invitations;

    alter table if exists user_invitations 
       add constraint FKfv40qt0xf7x55wko9qfravt7o 
       foreign key (business_id) 
       references businesses;

    alter table if exists user_invitations 
       add constraint FK5ocw8tunrbl8228n1owdf02p 
       foreign key (invited_by) 
       references users;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
