
    create table cart_items (
        quantity integer not null,
        total_price numeric(38,2),
        unit_price numeric(38,2),
        cart_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint,
        updated_at timestamp(6),
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table carts (
        total_amount numeric(38,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        user_id bigint unique,
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table categories (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(255),
        name varchar(255) not null,
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table images (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        product_id bigint,
        updated_at timestamp(6),
        created_by varchar(255),
        download_url varchar(255),
        file_name varchar(255),
        file_path varchar(255) not null,
        file_type varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table order_items (
        price numeric(38,2),
        quantity integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_id bigint,
        product_id bigint,
        updated_at timestamp(6),
        created_by varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table orders (
        total_amount numeric(38,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        order_date timestamp(6),
        updated_at timestamp(6),
        user_id bigint,
        created_by varchar(255),
        order_status varchar(255) check (order_status in ('PENDING','PROCESSING','SHIPPED','DELIVERED','CANCELLED')),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table products (
        inventory integer not null,
        price numeric(38,2),
        category_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        brand varchar(255),
        created_by varchar(255),
        description varchar(255),
        name varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(255),
        email varchar(255) not null unique,
        first_name varchar(255),
        last_name varchar(255),
        password varchar(255),
        slug varchar(255) not null unique,
        updated_by varchar(255),
        primary key (id)
    );

    alter table if exists cart_items 
       add constraint FKpcttvuq4mxppo8sxggjtn5i2c 
       foreign key (cart_id) 
       references carts;

    alter table if exists cart_items 
       add constraint FK1re40cjegsfvw58xrkdp6bac6 
       foreign key (product_id) 
       references products;

    alter table if exists carts 
       add constraint FKb5o626f86h46m4s7ms6ginnop 
       foreign key (user_id) 
       references users;

    alter table if exists images 
       add constraint FKghwsjbjo7mg3iufxruvq6iu3q 
       foreign key (product_id) 
       references products;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;
