CREATE TABLE roles (
   id bigint generated by default as identity,
   slug varchar(255) not null unique,
   name varchar(100) not null unique,
   created_by varchar(255),
   updated_by varchar(255),
   created_at timestamp(6) not null,
   updated_at timestamp(6),
   primary key (id)
);

CREATE TABLE user_roles (
    user_id bigint not null,
    role_id bigint not null,

    primary key (user_id, role_id),

    constraint fk_user_roles_user
        foreign key (user_id)
            references users(id)
            on delete cascade,

    constraint fk_user_roles_role
        foreign key (role_id)
            references roles(id)
            on delete cascade
);